cc_library (
    name = "base_game",
    hdrs = ["base_game.h"],
    srcs = ["base_game.cpp"],
    deps = [
        "//framework/config:config",
        "//framework/window:window",
        "//framework/input_handler:input_handler",
    ],
    visibility = ["//visibility:public",],
)
