cc_library (
    name = "level_manager",
    hdrs = ["level.h", "level_manager.h",],
    srcs = [ "level_manager.cpp",],
    deps = [
        "@SDL2//:SDL2",
        "//framework/input_handler:input_handler",
        "//framework/world:world",
    ],
    visibility = ["//visibility:public"],
)