cc_library (
    name = "config",
    hdrs = ["configuration.h",],
    srcs = ["configuration.cpp",],
    deps = [
        "@SDL2//:SDL2",
        "@SDL2//:SDL2main",
        "@SDL2//:SDL2image",
        "@SDL2//:SDL2ttf",
        "@SDL2//:SDL2mixer",
        "//framework/linear_algebra:linalg",
    ],
    visibility = ["//visibility:public"],
)